name: flutter_application_1
description: "Serene - Mental Health App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  fl_chart: ^0.69.0
  audioplayers: ^6.5.1
  google_generative_ai: ^0.4.0
  provider: ^6.1.2
  uuid: ^4.5.2
  intl: ^0.20.2
  http: ^0.13.6
  flutter_markdown: ^0.6.18
  share_plus: ^7.2.1
  flutter_tts: ^3.8.3
  pdf: ^3.11.1
  printing: ^5.13.3
  path_provider: ^2.1.4
  image_picker: ^1.1.2

  # Camera untuk rPPG
  camera: ^0.10.5+5

  # Face Detection dengan ML Kit
  google_mlkit_face_detection: ^0.9.0

  # Image Processing untuk RGB extraction
  image: ^4.1.3

  # Accelerometer Sensor
  sensors_plus: ^4.0.0

  # Firebase Dependencies - TAMBAHKAN INI
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  # Temporary override to resolve http / other package conflicts.
  # Consider removing after adjusting dependent package versions.
  http: ^1.5.0

flutter:
  uses-material-design: true

  # Perbaikan ada di sini.
  # Blok 'assets' sekarang berada di DALAM 'flutter'
  # dan kita hanya mendaftarkan foldernya.
  assets:
    - assets/audio/sunday_driver_loop_401994.mp3
    - assets/audio/meditation-background-music-383120.mp3
    - assets/audio/meditation-music-338902.mp3
    - assets/audio/meditation-music-427644.mp3
    - assets/audio/meditation-yoga-relaxing-music-380330.mp3
    - assets/audio/sleep-music-vol16-195422.mp3

    - assets/images/meditasi_stress_tempat_kerja.jpg
    - assets/images/Hubungan_Sehat.jpg
    - assets/images/Kecemasan_Sosial.jpg
    - assets/images/Mengenal_Mindfulness.jpg
    - assets/images/Menulis_Jurnal.jpg
    - assets/images/Tidur_Berkualitas.webp

    - assets/images/Pagi_Hari.jpg
    - assets/images/Tidur_Lelap.webp
    - assets/images/Fokus_Sepenuhnya.jpg
    - assets/images/Meditasi_Pemula.jpg
    - assets/images/Mengatasi_Kecemasan.jpg
    - assets/images/Meditasi_Pernapasan.webp
    - assets/images/Energi_Pagi.jpg
    - assets/images/Tidur_Cepat.webp
    - assets/images/Meditasi_Gratitude.jpg
    - assets/images/Konsentrasi_Belajar.jpg
    - assets/images/Relaksasi_Mendalam.jpg
    - assets/images/Tidur_Restoratif.jpg
    - assets/images/LOGO.webp
    - assets/images/riwayat.png
    - assets/images/jurnal_home.jpg
    - assets/images/Meditasi_emang_berpengaruh.webp
    - assets/images/Lakukan_Meditasi_Sebelum_Belajar.webp
    - assets/images/Meditasi_Penyembuhan_Penyakit.jpg
      # File data dokter
    - assets/data/doctors.json
